package config

type serverPropertiesJavaV1 struct {
    acceptsTransfers                bool
    allowNether                     bool
    broadcastConsoleToOps           bool
    broadcastRconToOps              bool
    bugReportLink                   string
    difficulty                      string
    enableCommandBlock              bool
    enableJmxMonitoring             bool
    enableQuery                     bool
    enableRcon                      bool
    enableStatus                    bool
    enforceSecureProfile            bool
    enforceWhitelist                bool
    entityBroadcastRangePercentage  int
    forceGameMode                   bool
    functionPermissionLevel         string
    gameMode                        string
    generateStructures              bool
    generatorSettings               string
    hardcore                        bool
    hideOnlinePlayers               bool
    initialDisabledPacks            string
    initialEnabledPacks             string
    levelName                       string
    levelSeed                       string
    levelType                       string
    logIps                          bool
    maxChainedNeighbourUpdates      int
    maxPlayers                      int
    maxTickTime                     int
    maxWorldSize                    int
    motd                            string
    networkCompressionThreshold     string
    onlineMode                      string
    opPermissionLevel               string
    pauseWhenEmptySeconds           int
    playerIdleTimeout               int
    preventProxyConnections         bool
    pvp                             bool
    queryPort                       int
    rateLimit                       int
    rconPassword                    string
    rconPort                        int
    regionFileCompression           string
    requireResourcePack             bool
    resourcePackId                  string
    resourcePackPrompt              string
    resourcePackSha1                string
    serverIp                        string
    serverPort                      string
    simulationDistance              int
    spawnMonsters                   bool
    spawnProtection                 int
    syncChunkWrites                 bool
    textFilteringConfig             string
    textFilteringVersion            int
    useNativeTransport              bool
    viewDistance                    int
    whiteList                       bool
}
